#!/bin/sh
set -e

: "${REACT_APP_BACKEND_URL:=${BACKEND_URL:-}}"
: "${REACT_APP_NAME_SYSTEM:=ChatIA}"
: "${REACT_APP_COMPANY_NAME:=${COMPANY_NAME:-ChatIA}}"
: "${REACT_APP_NUMBER_SUPPORT:=${CONTACT_PHONE:-}}"
: "${REACT_APP_HOURS_CLOSE_TICKETS_AUTO:=9999}"
: "${REACT_APP_PRIMARY_COLOR:=#6B46C1}"
: "${REACT_APP_PRIMARY_DARK:=#4C1D95}"
: "${REACT_APP_FACEBOOK_APP_ID:=${FACEBOOK_APP_ID:-}}"
: "${REACT_APP_REQUIRE_BUSINESS_MANAGEMENT:=FALSE}"

escape_js() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

cat > /usr/share/nginx/html/env-config.js <<EOF
window.ENV = {
  REACT_APP_BACKEND_URL: "$(escape_js "$REACT_APP_BACKEND_URL")",
  REACT_APP_NAME_SYSTEM: "$(escape_js "$REACT_APP_NAME_SYSTEM")",
  REACT_APP_COMPANY_NAME: "$(escape_js "$REACT_APP_COMPANY_NAME")",
  REACT_APP_NUMBER_SUPPORT: "$(escape_js "$REACT_APP_NUMBER_SUPPORT")",
  REACT_APP_HOURS_CLOSE_TICKETS_AUTO: "$(escape_js "$REACT_APP_HOURS_CLOSE_TICKETS_AUTO")",
  REACT_APP_PRIMARY_COLOR: "$(escape_js "$REACT_APP_PRIMARY_COLOR")",
  REACT_APP_PRIMARY_DARK: "$(escape_js "$REACT_APP_PRIMARY_DARK")",
  REACT_APP_FACEBOOK_APP_ID: "$(escape_js "$REACT_APP_FACEBOOK_APP_ID")",
  REACT_APP_REQUIRE_BUSINESS_MANAGEMENT: "$(escape_js "$REACT_APP_REQUIRE_BUSINESS_MANAGEMENT")"
};
EOF
